server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:9002/
          predicates:
          - Path=/**
          filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter:
                replenishRate: 1
                burstCapacity: 2
                requestedTokens: 1
          
        - id: driver-service
          uri: http://localhost:9001/
          predicates:
          - Path=/**

  redis:
    database: 0
    host: localhost
    port: 6379